wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.24
    framework: sklearn
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.9
    t:
      1:
      - 5
      4: 3.7.9
      5: 0.10.24
      8:
      - 1
      - 3
      - 5
max_depth:
  desc: null
  value: 4
