wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.24
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.9
    t:
      1:
      - 5
      - 8
      4: 3.7.9
      5: 0.10.24
      8:
      - 1
      - 3
      - 5
    viz:
      class_proportions:
        historyFieldSettings:
          key: class_proportions
          x-axis: _step
        id: wandb/class_proportions/v1
      confusion_matrix:
        historyFieldSettings:
          key: confusion_matrix
          x-axis: _step
        id: wandb/confusion_matrix/v1
      feature_importances:
        historyFieldSettings:
          key: feature_importances
          x-axis: _step
        id: wandb/feature_importances/v1
      learning_curve:
        historyFieldSettings:
          key: learning_curve
          x-axis: _step
        id: wandb/learning_curve/v1
      summary_metrics:
        historyFieldSettings:
          key: summary_metrics
          x-axis: _step
        id: wandb/metrics/v1
max_depth:
  desc: null
  value: 2
